# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 11:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('post_bar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postbar',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='\u8d34\u5427\u521b\u5efa\u65f6\u95f4'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postbar',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_bar', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='postbar',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managing_bar', to=settings.AUTH_USER_MODEL),
        ),
    ]
