# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 01:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_bar', '0002_auto_20170414_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='preview',
            field=models.CharField(default='aa', max_length=250, verbose_name=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postbar',
            name='description',
            field=models.CharField(default='descriptin', max_length=200, verbose_name='\u8d34\u5427\u63cf\u8ff0'),
            preserve_default=False,
        ),
    ]
