# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 15:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post_bar', '0003_auto_20170415_0150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='child_comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='father_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_comment', to='post_bar.Comment'),
        ),
        migrations.AddField(
            model_name='postbar',
            name='cover',
            field=models.ImageField(default='corvers/default.jpg', upload_to='covers/', verbose_name='\u5c01\u9762'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='commenter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='avatars/default.jpg', upload_to='avatars/', verbose_name='\u5934\u50cf'),
        ),
    ]
