# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 12:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post_bar', '0004_auto_20170415_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unread', models.BooleanField(default=True, verbose_name='\u672a\u8bfb')),
                ('triggered_time', models.DateTimeField(auto_now_add=True, verbose_name='\u89e6\u53d1\u65f6\u95f4')),
                ('action_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_notifications', to='post_bar.Comment')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('trigger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggered_notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
