# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 07:32
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_bar', '0006_post_update_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='\u5e16\u5b50\u5185\u5bb9'),
        ),
    ]
