# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 09:39
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_bar', '0007_auto_20170417_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='\u5e16\u5b50\u5185\u5bb9'),
        ),
    ]
